"""destinations and deliveries

Revision ID: 234a535fcabe
Revises: c9a2396adb26
Create Date: 2026-07-26 10:41:46.983616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '234a535fcabe'
down_revision: Union[str, Sequence[str], None] = 'c9a2396adb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filter', sa.String(), nullable=False),
    sa.Column('transform', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('batch_window_s', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_source_id'), 'destinations', ['source_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('destination_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_claim', 'deliveries', ['status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_deliveries_destination_id'), 'deliveries', ['destination_id'], unique=False)
    op.create_index(op.f('ix_deliveries_event_id'), 'deliveries', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_event_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_destination_id'), table_name='deliveries')
    op.drop_index('ix_deliveries_claim', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_destinations_source_id'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
