"""delivery claimed_at

Revision ID: 5a52e8c3ea6c
Revises: 234a535fcabe
Create Date: 2026-07-26 10:51:19.383156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a52e8c3ea6c'
down_revision: Union[str, Sequence[str], None] = '234a535fcabe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'claimed_at')
    # ### end Alembic commands ###
